<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd5497be666e98015b67c53b556b3657e
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Liu\\AliyunGreen\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Liu\\AliyunGreen\\' => 
        array (
            0 => __DIR__ . '/..' . '/hank/aliyun-green/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd5497be666e98015b67c53b556b3657e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd5497be666e98015b67c53b556b3657e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
